### ISSUE TITLE
Error installing Github

### ISSUE THREAD

**Issue by mvanzonneveld** [CIAT-DAPA/GapAnalysis#10]
Loading required package: raster
Error: package or namespace load failed for ‘raster’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘Rcpp’
Error in .requirePackage(package) : 
  unable to find required package ‘raster’
Loading required package: raster
Error: package or namespace load failed for ‘raster’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘Rcpp’
Error in .requirePackage(package) : 
  unable to find required package ‘raster’
Loading required package: raster
Error: package or namespace load failed for ‘raster’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘Rcpp’
Error in .requirePackage(package) : 
  unable to find required package ‘raster’

**Comment by dcarver1** [comment]
associated with Error #11
