### ISSUE TITLE
Error installing Gap analysis 

### ISSUE THREAD

**Issue by mvanzonneveld** [CIAT-DAPA/GapAnalysis#11]
These errors appears:

Loading required package: raster
Error: package or namespace load failed for ‘raster’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘Rcpp’
Error in .requirePackage(package) : 
  unable to find required package ‘raster’
Loading required package: raster
Error: package or namespace load failed for ‘raster’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘Rcpp’
Error in .requirePackage(package) : 
  unable to find required package ‘raster’
Loading required package: raster
Error: package or namespace load failed for ‘raster’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘Rcpp’
Error in .requirePackage(package) : 
  unable to find required package ‘raster’

**Comment by kauedesousa** [comment]
Try to remove the package raster with`remove.packages()` and then install Rcpp and then install raster again. 

The problem might be in the versioning of either raster or Rcpp

**Comment by mvanzonneveld** [comment]
Thaks Kaue,

The following error also appears: 
Error in rbind(info, getNamespaceInfo(env, "S3methods")) : 
  number of columns of matrices must match (see arg 2)
ERROR: lazy loading failed for package 'GapAnalysis'

Any idea how to solve this?

**Comment by kauedesousa** [comment]
This seems to be an issue when the function file contains an uncommented code. But I don't think that this is the problem here. I removed the pkgs raster and Rcpp, and then installed GapAnalysis and it went fine.  

Could you run `sessioninfo::session_info()` to get an info on your current R session? Mine is this one and it went fine. 

```
> sessioninfo::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.6      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Oslo                 
 date     2020-08-18                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version  date       lib source        
 abind          1.4-5    2016-07-21 [1] CRAN (R 4.0.0)
 assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
 base64enc      0.1-3    2015-07-28 [1] CRAN (R 4.0.0)
 class          7.3-17   2020-04-26 [1] CRAN (R 4.0.2)
 classInt       0.4-3    2020-04-07 [1] CRAN (R 4.0.0)
 cli            2.0.2    2020-02-28 [1] CRAN (R 4.0.0)
 codetools      0.2-16   2018-12-24 [1] CRAN (R 4.0.2)
 crayon         1.3.4    2017-09-16 [1] CRAN (R 4.0.0)
 crosstalk      1.1.0.1  2020-03-13 [1] CRAN (R 4.0.0)
 data.table     1.12.8   2019-12-09 [1] CRAN (R 4.0.0)
 dataverse      0.2.0    2017-06-15 [1] CRAN (R 4.0.0)
 DBI            1.1.0    2019-12-15 [1] CRAN (R 4.0.0)
 dichromat      2.0-0    2013-01-24 [1] CRAN (R 4.0.0)
 digest         0.6.25   2020-02-23 [1] CRAN (R 4.0.0)
 dplyr          1.0.0    2020-05-29 [1] CRAN (R 4.0.0)
 e1071          1.7-3    2019-11-26 [1] CRAN (R 4.0.0)
 ellipsis       0.3.1    2020-05-15 [1] CRAN (R 4.0.0)
 evaluate       0.14     2019-05-28 [1] CRAN (R 4.0.0)
 fansi          0.4.1    2020-01-08 [1] CRAN (R 4.0.0)
 fasterize      1.0.2    2020-03-25 [1] CRAN (R 4.0.0)
 GapAnalysis  * 1.0.1    2020-08-10 [1] CRAN (R 4.0.2)
 generics       0.0.2    2018-11-29 [1] CRAN (R 4.0.0)
 geosphere      1.5-10   2019-05-26 [1] CRAN (R 4.0.0)
 glue           1.4.1    2020-05-13 [1] CRAN (R 4.0.0)
 htmltools      0.5.0    2020-06-16 [1] CRAN (R 4.0.0)
 htmlwidgets    1.5.1    2019-10-08 [1] CRAN (R 4.0.0)
 httr           1.4.1    2019-08-05 [1] CRAN (R 4.0.0)
 KernSmooth     2.23-17  2020-04-26 [1] CRAN (R 4.0.2)
 knitr          1.29     2020-06-23 [1] CRAN (R 4.0.2)
 lattice        0.20-41  2020-04-02 [1] CRAN (R 4.0.2)
 leafem         0.1.3    2020-07-26 [1] CRAN (R 4.0.2)
 leaflet        2.0.3    2019-11-16 [1] CRAN (R 4.0.2)
 leafsync       0.1.0    2019-03-05 [1] CRAN (R 4.0.0)
 lifecycle      0.2.0    2020-03-06 [1] CRAN (R 4.0.0)
 lwgeom         0.2-5    2020-06-12 [1] CRAN (R 4.0.0)
 magrittr       1.5      2014-11-22 [1] CRAN (R 4.0.0)
 pillar         1.4.6    2020-07-10 [1] CRAN (R 4.0.2)
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.0.0)
 png            0.1-7    2013-12-03 [1] CRAN (R 4.0.2)
 purrr          0.3.4    2020-04-17 [1] CRAN (R 4.0.0)
 R6             2.4.1    2019-11-12 [1] CRAN (R 4.0.0)
 raster       * 3.3-13   2020-07-17 [1] CRAN (R 4.0.2)
 RColorBrewer   1.1-2    2014-12-07 [1] CRAN (R 4.0.0)
 Rcpp           1.0.5    2020-07-06 [1] CRAN (R 4.0.2)
 rlang          0.4.7    2020-07-09 [1] CRAN (R 4.0.2)
 rmarkdown      2.3      2020-06-18 [1] CRAN (R 4.0.2)
 rstudioapi     0.11     2020-02-07 [1] CRAN (R 4.0.0)
 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 4.0.0)
 sf             0.9-5    2020-07-14 [1] CRAN (R 4.0.2)
 sp           * 1.4-2    2020-05-20 [1] CRAN (R 4.0.0)
 stars          0.4-3    2020-07-08 [1] CRAN (R 4.0.2)
 tibble         3.0.3    2020-07-10 [1] CRAN (R 4.0.2)
 tidyselect     1.1.0    2020-05-11 [1] CRAN (R 4.0.0)
 tmap           3.1      2020-07-09 [1] CRAN (R 4.0.2)
 tmaptools      3.1      2020-07-01 [1] CRAN (R 4.0.0)
 units          0.6-7    2020-06-13 [1] CRAN (R 4.0.0)
 vctrs          0.3.2    2020-07-15 [1] CRAN (R 4.0.0)
 viridisLite    0.3.0    2018-02-01 [1] CRAN (R 4.0.0)
 withr          2.2.0    2020-04-20 [1] CRAN (R 4.0.0)
 xfun           0.15     2020-06-21 [1] CRAN (R 4.0.0)
 XML            3.99-0.4 2020-07-05 [1] CRAN (R 4.0.2)
 xml2           1.3.2    2020-04-23 [1] CRAN (R 4.0.0)

```

**Comment by mvanzonneveld** [comment]
Hi Kaue,

Thank you so much. That might be the case. I am still in version 3.5… Que
pena!

Maarten



- Session info
--------------------------------------------------------------------------

setting  value

 version  R version 3.5.2 (2018-12-20)

os       Windows >= 8 x64

 system   x86_64, mingw32

 ui       RStudio

 language (EN)

 collate  English_United States.1252

 ctype    English_United States.1252

 tz       Asia/Taipei

 date     2020-08-18



- Packages
------------------------------------------------------------------------------

package     * version date       lib source

 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)

cli           2.0.2   2020-02-28 [1] CRAN (R 3.5.3)

crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)

fansi         0.4.1   2020-01-08 [1] CRAN (R 3.5.3)

glue          1.4.0   2020-04-03 [1] CRAN (R 3.5.3)

lattice       0.20-38 2018-11-04 [2] CRAN (R 3.5.2)

rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.5.3)

sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)

sp          * 1.4-1   2020-02-28 [1] CRAN (R 3.5.3)

withr         2.2.0   2020-04-20 [1] CRAN (R 3.5.3)

yaml          2.2.1   2020-02-01 [1] CRAN (R 3.5.3)



[1] D:/Documents and Settings/maarten.vanzonneveld/My
Documents/R/win-library/3.5

[2] C:/Program Files/R/R-3.5.2/library





*From:* Kauê de Sousa [mailto:notifications@github.com]
*Sent:* Tuesday, August 18, 2020 3:11 PM
*To:* CIAT-DAPA/GapAnalysis <GapAnalysis@noreply.github.com>
*Cc:* mvanzonneveld <maarten.vanzonneveld@worldveg.org>; Author <
author@noreply.github.com>
*Subject:* Re: [CIAT-DAPA/GapAnalysis] Error installing Gap analysis (#11)



This seems to be an issue when the function file contains an uncommented
code. But I don't think that this is the problem here. I removed the pkgs
raster and Rcpp, and then installed GapAnalysis and it went fine.

Could you run sessioninfo::session_info() to get an info on your current R
session? Mine is this one and it went fine.

> sessioninfo::session_info()



─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────



 setting  value



 version  R version 4.0.2 (2020-06-22)



 os       macOS Catalina 10.15.6



 system   x86_64, darwin17.0



 ui       RStudio



 language (EN)



 collate  en_US.UTF-8



 ctype    en_US.UTF-8



 tz       Europe/Oslo



 date     2020-08-18







─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────



 package      * version  date       lib source



 abind          1.4-5    2016-07-21 [1] CRAN (R 4.0.0)



 assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.0.0)



 base64enc      0.1-3    2015-07-28 [1] CRAN (R 4.0.0)



 class          7.3-17   2020-04-26 [1] CRAN (R 4.0.2)



 classInt       0.4-3    2020-04-07 [1] CRAN (R 4.0.0)



 cli            2.0.2    2020-02-28 [1] CRAN (R 4.0.0)



 codetools      0.2-16   2018-12-24 [1] CRAN (R 4.0.2)



 crayon         1.3.4    2017-09-16 [1] CRAN (R 4.0.0)



 crosstalk      1.1.0.1  2020-03-13 [1] CRAN (R 4.0.0)



 data.table     1.12.8   2019-12-09 [1] CRAN (R 4.0.0)



 dataverse      0.2.0    2017-06-15 [1] CRAN (R 4.0.0)



 DBI            1.1.0    2019-12-15 [1] CRAN (R 4.0.0)



 dichromat      2.0-0    2013-01-24 [1] CRAN (R 4.0.0)



 digest         0.6.25   2020-02-23 [1] CRAN (R 4.0.0)



 dplyr          1.0.0    2020-05-29 [1] CRAN (R 4.0.0)



 e1071          1.7-3    2019-11-26 [1] CRAN (R 4.0.0)



 ellipsis       0.3.1    2020-05-15 [1] CRAN (R 4.0.0)



 evaluate       0.14     2019-05-28 [1] CRAN (R 4.0.0)



 fansi          0.4.1    2020-01-08 [1] CRAN (R 4.0.0)



 fasterize      1.0.2    2020-03-25 [1] CRAN (R 4.0.0)



 GapAnalysis  * 1.0.1    2020-08-10 [1] CRAN (R 4.0.2)



 generics       0.0.2    2018-11-29 [1] CRAN (R 4.0.0)



 geosphere      1.5-10   2019-05-26 [1] CRAN (R 4.0.0)



 glue           1.4.1    2020-05-13 [1] CRAN (R 4.0.0)



 htmltools      0.5.0    2020-06-16 [1] CRAN (R 4.0.0)



 htmlwidgets    1.5.1    2019-10-08 [1] CRAN (R 4.0.0)



 httr           1.4.1    2019-08-05 [1] CRAN (R 4.0.0)



 KernSmooth     2.23-17  2020-04-26 [1] CRAN (R 4.0.2)



 knitr          1.29     2020-06-23 [1] CRAN (R 4.0.2)



 lattice        0.20-41  2020-04-02 [1] CRAN (R 4.0.2)



 leafem         0.1.3    2020-07-26 [1] CRAN (R 4.0.2)



 leaflet        2.0.3    2019-11-16 [1] CRAN (R 4.0.2)



 leafsync       0.1.0    2019-03-05 [1] CRAN (R 4.0.0)



 lifecycle      0.2.0    2020-03-06 [1] CRAN (R 4.0.0)



 lwgeom         0.2-5    2020-06-12 [1] CRAN (R 4.0.0)



 magrittr       1.5      2014-11-22 [1] CRAN (R 4.0.0)



 pillar         1.4.6    2020-07-10 [1] CRAN (R 4.0.2)



 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.0.0)



 png            0.1-7    2013-12-03 [1] CRAN (R 4.0.2)



 purrr          0.3.4    2020-04-17 [1] CRAN (R 4.0.0)



 R6             2.4.1    2019-11-12 [1] CRAN (R 4.0.0)



 raster       * 3.3-13   2020-07-17 [1] CRAN (R 4.0.2)



 RColorBrewer   1.1-2    2014-12-07 [1] CRAN (R 4.0.0)



 Rcpp           1.0.5    2020-07-06 [1] CRAN (R 4.0.2)



 rlang          0.4.7    2020-07-09 [1] CRAN (R 4.0.2)



 rmarkdown      2.3      2020-06-18 [1] CRAN (R 4.0.2)



 rstudioapi     0.11     2020-02-07 [1] CRAN (R 4.0.0)



 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 4.0.0)



 sf             0.9-5    2020-07-14 [1] CRAN (R 4.0.2)



 sp           * 1.4-2    2020-05-20 [1] CRAN (R 4.0.0)



 stars          0.4-3    2020-07-08 [1] CRAN (R 4.0.2)



 tibble         3.0.3    2020-07-10 [1] CRAN (R 4.0.2)



 tidyselect     1.1.0    2020-05-11 [1] CRAN (R 4.0.0)



 tmap           3.1      2020-07-09 [1] CRAN (R 4.0.2)



 tmaptools      3.1      2020-07-01 [1] CRAN (R 4.0.0)



 units          0.6-7    2020-06-13 [1] CRAN (R 4.0.0)



 vctrs          0.3.2    2020-07-15 [1] CRAN (R 4.0.0)



 viridisLite    0.3.0    2018-02-01 [1] CRAN (R 4.0.0)



 withr          2.2.0    2020-04-20 [1] CRAN (R 4.0.0)



 xfun           0.15     2020-06-21 [1] CRAN (R 4.0.0)



 XML            3.99-0.4 2020-07-05 [1] CRAN (R 4.0.2)



 xml2           1.3.2    2020-04-23 [1] CRAN (R 4.0.0)







—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CIAT-DAPA/GapAnalysis/issues/11#issuecomment-675300090>,
or unsubscribe

**Comment by dcarver1** [comment]
thank you for the comments Kaue, 
This seems to be connected with a local installation problem and is not a function of the package.
