### ISSUE TITLE
Error in .check_input(xy, dist_m, step_dg, crs, output) :    could not find function ".check_input"

### ISSUE THREAD

**Issue by mvanzonneveld** [CIAT-DAPA/GapAnalysis#12]
I receive the following error in the gbuffer function:
" Error in .check_input(xy, dist_m, step_dg, crs, output) : 
  could not find function ".check_input" "
Any idea what this error means and how to solve it?

**Comment by dcarver1** [comment]
This was resulting from passing a projected SP object into the gBuffer function. I removed this and passed a data frame instead. That resolved the issue on my end.
